package common;

public enum MessageType {
    PUBLIC,
    PRIVATE,
    CLIENT_LIST,
    SEND_AUTH,
    AUTH_CONFIRM,
    AUTH_FAILED,
    AUTH_DOUBLE,
    CHANGE_USERNAME,
    CHANGE_USERNAME_FAILED,
    CHANGE_USERNAME_CONFIRM,
    CHANGE_PASSWORD,
    CHANGE_PASSWORD_FAILED,
    CHANGE_PASSWORD_CONFIRM,
    SEND_REGISTRATION,
    SEND_REGISTRATION_CONFIRM,
    SEND_REGISTRATION_FAILED,

}